#!/bin/bash
# Generated by Copilot
# Ollama initialization script để tự động pull models cần thiết

set -e

echo "🚀 Starting Ollama server..."

# Start Ollama server in background
/bin/ollama serve &
OLLAMA_PID=$!

# Wait for Ollama to be ready
echo "⏳ Waiting for Ollama server to be ready..."
for i in {1..30}; do
    # Check if Ollama server is responding by trying to list running models
    if ollama ps >/dev/null 2>&1; then
        echo "✅ Ollama server is ready!"
        echo "📦 Pulling nomic-embed-text model..."
        ollama pull nomic-embed-text
        echo "🎉 Model nomic-embed-text is ready!"
        break
    fi
    echo "   Attempt $i/30: Ollama not ready yet, waiting 5 seconds..."
    sleep 5
done

# Check if Ollama is ready
if ! ollama ps >/dev/null 2>&1; then
    echo "❌ Failed to start Ollama server after 150 seconds"
    exit 1
fi

echo "📊 Available models:"
ollama list

# Keep Ollama server running
wait $OLLAMA_PID
