# Generated by Copilot
"""
Core Application Components

Package containing core application functionality and lifecycle management.
"""

from .lifecycle import lifecycle_manager, lifespan

__all__ = ["lifecycle_manager", "lifespan"]
