# Generated by Copilot
"""
WebSocket Connection Manager Package

Package for managing WebSocket connections in PolyMind chat system.
"""

from .connection_manager import ws_connection_manager

__all__ = ["ws_connection_manager"]
