// Generated by Copilot

class PolyMindChat {
    constructor() {
        this.apiBaseUrl = window.location.origin;
        this.wsUrl = `ws://${window.location.host}/ws/chat`;
        this.messages = [];
        this.isTyping = false;
        this.selectedAgent = 'general';
        this.websocket = null;
        this.reconnectAttempts = 0;
        this.maxReconnectAttempts = 5;
        
        this.init();
    }

    init() {
        this.setupEventListeners();
        this.setupTextarea();
        this.updateWelcomeTime();
        this.setupAgentSelector();
        this.connectWebSocket();
        this.setupSidebar();
        
        console.log('🧠 PolyMind Chat initialized with WebSocket and Sidebar');
    }    /**
     * Khởi tạo WebSocket connection với error handling cải tiến
     */
    connectWebSocket() {
        try {
            this.websocket = new WebSocket(this.wsUrl);
            
            this.websocket.onopen = () => {
                console.log('✅ WebSocket connected');
                this.updateConnectionStatus('connected');
                this.reconnectAttempts = 0;
                
                // Thêm animation cho status dot khi connected
                this.animateStatusDot('success');
            };

            this.websocket.onmessage = (event) => {
                const data = JSON.parse(event.data);
                this.handleWebSocketMessage(data);
            };

            this.websocket.onclose = () => {
                console.log('❌ WebSocket disconnected');
                this.updateConnectionStatus('disconnected');
                this.animateStatusDot('error');
                this.attemptReconnect();
            };

            this.websocket.onerror = (error) => {
                console.error('🚨 WebSocket error:', error);
                this.updateConnectionStatus('disconnected');
                this.animateStatusDot('error');
            };

        } catch (error) {
            console.error('Failed to connect WebSocket:', error);
            this.updateConnectionStatus('disconnected');
            this.animateStatusDot('error');
        }
    }

    attemptReconnect() {
        if (this.reconnectAttempts < this.maxReconnectAttempts) {
            this.reconnectAttempts++;
            this.updateConnectionStatus('connecting');
            
            setTimeout(() => {
                console.log(`🔄 Reconnect attempt ${this.reconnectAttempts}/${this.maxReconnectAttempts}`);
                this.connectWebSocket();
            }, 2000 * this.reconnectAttempts);
        }
    }

    handleWebSocketMessage(data) {
        if (data.type === 'ai_response') {
            this.hideTyping();
            this.addMessage(data.content, 'ai');
        }
    }    /**
     * Cập nhật trạng thái kết nối với UI cải tiến
     * @param {string} status - Trạng thái kết nối ('connected', 'disconnected', 'connecting')
     */
    updateConnectionStatus(status) {
        const connectionStatus = document.getElementById('connectionStatus');
        const statusText = document.getElementById('statusText');
        
        if (!connectionStatus) return;
        
        connectionStatus.className = `connection-status ${status}`;
        
        // Map trạng thái sang text tiếng Việt
        const statusMessages = {
            'connected': 'Đã kết nối',
            'disconnected': 'Mất kết nối',
            'connecting': 'Đang kết nối...'
        };
        
        const message = statusMessages[status] || 'Không xác định';
        
        // Cập nhật tooltip
        connectionStatus.setAttribute('data-status', message);
        
        // Cập nhật text element nếu có
        if (statusText) {
            statusText.textContent = message;
        }
        
        // Log cho debugging
        console.log(`🔌 Connection status: ${status} (${message})`);
    }

    setupEventListeners() {
        // Chat form submission
        const chatForm = document.getElementById('chatForm');
        chatForm.addEventListener('submit', (e) => {
            e.preventDefault();
            this.sendMessage();
        });

        // Textarea auto-resize and shortcuts
        const chatInput = document.getElementById('chatInput');
        chatInput.addEventListener('input', () => {
            this.updateCharCount();
            this.autoResizeTextarea();
            this.updateSendButton();
        });

        chatInput.addEventListener('keydown', (e) => {
            if (e.key === 'Enter' && !e.shiftKey) {
                e.preventDefault();
                this.sendMessage();
            }
        });

        // Send button
        const sendButton = document.getElementById('sendButton');
        sendButton.addEventListener('click', () => {
            this.sendMessage();
        });
    }

    setupTextarea() {
        const chatInput = document.getElementById('chatInput');
        chatInput.style.height = 'auto';
        this.updateSendButton();
    }

    setupAgentSelector() {
        const agentSelector = document.getElementById('agentSelector');
        agentSelector.addEventListener('change', (e) => {
            this.selectedAgent = e.target.value;
            this.addSystemMessage(`Đã chuyển sang ${e.target.options[e.target.selectedIndex].text}`);
        });
    }

    updateWelcomeTime() {
        const welcomeTime = document.getElementById('welcomeTime');
        if (welcomeTime) {
            welcomeTime.textContent = new Date().toLocaleTimeString('vi-VN');
        }
    }

    updateCharCount() {
        const chatInput = document.getElementById('chatInput');
        const charCount = document.getElementById('charCount');
        const currentLength = chatInput.value.length;
        const maxLength = parseInt(chatInput.getAttribute('maxlength')) || 2000;
        
        charCount.textContent = `${currentLength}/${maxLength}`;
        
        // Change color if approaching limit
        if (currentLength > maxLength * 0.8) {
            charCount.style.color = 'var(--warning-color)';
        } else if (currentLength > maxLength * 0.9) {
            charCount.style.color = 'var(--error-color)';
        } else {
            charCount.style.color = 'var(--text-light)';
        }
    }

    autoResizeTextarea() {
        const chatInput = document.getElementById('chatInput');
        chatInput.style.height = 'auto';
        chatInput.style.height = Math.min(chatInput.scrollHeight, 120) + 'px';
    }

    updateSendButton() {
        const chatInput = document.getElementById('chatInput');
        const sendButton = document.getElementById('sendButton');
        const hasText = chatInput.value.trim().length > 0;
        
        sendButton.disabled = !hasText || this.isTyping;
    }    async sendMessage() {
        const chatInput = document.getElementById('chatInput');
        const message = chatInput.value.trim();
        
        if (!message || this.isTyping) return;

        // Check WebSocket connection
        if (!this.websocket || this.websocket.readyState !== WebSocket.OPEN) {
            this.addMessage('Kết nối bị gián đoạn. Đang thử kết nối lại...', 'ai', true);
            this.connectWebSocket();
            return;
        }

        // Add user message
        this.addMessage(message, 'user');
        
        // Clear input
        chatInput.value = '';
        this.updateCharCount();
        this.autoResizeTextarea();
        this.updateSendButton();

        // Show typing indicator
        this.showTyping();

        try {
            // Send message via WebSocket
            const messageData = {
                content: message,
                agent: this.selectedAgent,
                timestamp: new Date().toISOString()
            };
            
            this.websocket.send(JSON.stringify(messageData));
            
        } catch (error) {
            console.error('Error sending message:', error);
            this.hideTyping();
            this.addMessage('Xin lỗi, đã có lỗi xảy ra. Vui lòng thử lại.', 'ai', true);
        }
    }

    addMessage(content, sender, isError = false) {
        const chatMessages = document.getElementById('chatMessages');
        const messageDiv = document.createElement('div');
        const timestamp = new Date().toLocaleTimeString('vi-VN');
        const messageId = 'msg_' + Date.now();

        messageDiv.className = `message ${sender}`;
        messageDiv.id = messageId;

        const avatarContent = sender === 'user' ? 
            '<i class="fas fa-user"></i>' : 
            '<i class="fas fa-robot"></i>';

        const senderName = sender === 'user' ? 'Bạn' : 'AI Assistant';
        const messageClass = isError ? 'error-message' : '';

        messageDiv.innerHTML = `
            <div class="message-avatar">
                ${avatarContent}
            </div>
            <div class="message-bubble">
                <div class="message-content ${messageClass}">
                    ${this.formatMessage(content)}
                </div>
                <div class="message-time">${senderName} • ${timestamp}</div>
            </div>
        `;

        // Insert before typing indicator
        const typingIndicator = document.getElementById('typingIndicator');
        chatMessages.insertBefore(messageDiv, typingIndicator);

        // Animate message appearance
        messageDiv.style.opacity = '0';
        messageDiv.style.transform = 'translateY(20px)';
        
        setTimeout(() => {
            messageDiv.style.opacity = '1';
            messageDiv.style.transform = 'translateY(0)';
        }, 10);

        // Scroll to bottom
        this.scrollToBottom();

        // Store message
        this.messages.push({
            id: messageId,
            content,
            sender,
            timestamp: Date.now(),
            agent: this.selectedAgent
        });
    }

    addSystemMessage(content) {
        const chatMessages = document.getElementById('chatMessages');
        const messageDiv = document.createElement('div');
        
        messageDiv.innerHTML = `
            <div style="text-align: center; margin: var(--spacing-md) 0;">
                <div style="display: inline-block; background: var(--bg-primary); color: var(--text-secondary); padding: var(--spacing-xs) var(--spacing-md); border-radius: 20px; font-size: 0.875rem;">
                    <i class="fas fa-info-circle"></i> ${content}
                </div>
            </div>
        `;

        const typingIndicator = document.getElementById('typingIndicator');
        chatMessages.insertBefore(messageDiv, typingIndicator);
        this.scrollToBottom();
    }

    formatMessage(content) {
        // Basic message formatting
        return content
            .replace(/\n/g, '<br>')
            .replace(/`([^`]+)`/g, '<code>$1</code>')
            .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
            .replace(/\*([^*]+)\*/g, '<em>$1</em>');
    }

    showTyping() {
        this.isTyping = true;
        const typingIndicator = document.getElementById('typingIndicator');
        typingIndicator.style.display = 'flex';
        this.updateSendButton();
        this.scrollToBottom();
    }

    hideTyping() {
        this.isTyping = false;
        const typingIndicator = document.getElementById('typingIndicator');
        typingIndicator.style.display = 'none';
        this.updateSendButton();
    }

    async simulateAIResponse(userMessage) {
        // Simulate processing time
        await new Promise(resolve => setTimeout(resolve, 1000 + Math.random() * 2000));

        // Generate response based on agent type and user message
        const response = this.generateAIResponse(userMessage);
        this.addMessage(response, 'ai');
    }

    generateAIResponse(userMessage) {
        const responses = {
            general: [
                `Cảm ơn bạn đã hỏi "${userMessage}". Tôi sẽ giúp bạn tìm hiểu về vấn đề này.`,
                `Đây là một câu hỏi thú vị về "${userMessage}". Hãy để tôi phân tích và đưa ra câu trả lời chi tiết.`,
                `Tôi hiểu bạn muốn biết về "${userMessage}". Đây là những thông tin hữu ích tôi có thể chia sẻ.`
            ],
            coding: [
                `Về vấn đề lập trình "${userMessage}", tôi sẽ giúp bạn với code example và best practices.`,
                `Đây là một câu hỏi technical hay về "${userMessage}". Hãy để tôi giải thích chi tiết.`,
                `Tôi sẽ hỗ trợ bạn với "${userMessage}" bằng cách đưa ra solution và giải thích từng bước.`
            ],
            analysis: [
                `Tôi sẽ phân tích dữ liệu về "${userMessage}" và đưa ra insights quan trọng.`,
                `Về "${userMessage}", tôi sẽ thực hiện analysis chi tiết và đưa ra recommendations.`,
                `Dựa trên "${userMessage}", tôi sẽ cung cấp data-driven insights và visualizations.`
            ],
            creative: [
                `Tôi sẽ sáng tạo nội dung về "${userMessage}" với style độc đáo và engaging.`,
                `Về chủ đề "${userMessage}", tôi sẽ viết một cách creative và compelling.`,
                `Hãy để tôi tạo ra nội dung thú vị về "${userMessage}" với góc nhìn mới mẻ.`
            ]
        };

        const agentResponses = responses[this.selectedAgent] || responses.general;
        const randomResponse = agentResponses[Math.floor(Math.random() * agentResponses.length)];
        
        return randomResponse + '\n\nBạn có muốn tôi giải thích thêm chi tiết về vấn đề này không?';
    }

    scrollToBottom() {
        const chatMessages = document.getElementById('chatMessages');
        chatMessages.scrollTop = chatMessages.scrollHeight;
    }

    clearChat() {
        const chatMessages = document.getElementById('chatMessages');
        const messages = chatMessages.querySelectorAll('.message');
        
        messages.forEach(message => {
            if (!message.classList.contains('ai') || message.querySelector('.message-content p')) {
                message.remove();
            }
        });

        this.messages = [];
        this.addSystemMessage('Đã xóa lịch sử chat');
    }

    /**
     * Tạo animation cho status dot
     * @param {string} type - Loại animation ('success', 'error', 'warning')
     */
    animateStatusDot(type) {
        const statusDot = document.querySelector('.status-dot');
        if (!statusDot) return;
        
        // Xóa animation cũ
        statusDot.classList.remove('animate-success', 'animate-error', 'animate-warning');
        
        // Thêm animation mới
        statusDot.classList.add(`animate-${type}`);
        
        // Xóa class animation sau khi hoàn thành
        setTimeout(() => {
            statusDot.classList.remove(`animate-${type}`);
        }, 600);
    }

    /**
     * Toggle sidebar visibility trên mobile
     */    toggleSidebar() {
        const sidebar = document.querySelector('.sidebar');
        const overlay = document.querySelector('.sidebar-overlay');
        
        if (!sidebar) return;
        
        sidebar.classList.toggle('open');
        
        // Tạo overlay nếu chưa có
        if (!overlay) {
            const newOverlay = document.createElement('div');
            newOverlay.className = 'sidebar-overlay';
            newOverlay.addEventListener('click', () => this.closeSidebar());
            document.body.appendChild(newOverlay);
        }
        
        // Toggle overlay
        const currentOverlay = document.querySelector('.sidebar-overlay');
        if (sidebar.classList.contains('open')) {
            currentOverlay?.classList.add('show');
            document.body.style.overflow = 'hidden'; // Prevent scroll
        } else {
            currentOverlay?.classList.remove('show');
            document.body.style.overflow = '';
        }
    }    /**
     * Đóng sidebar
     */
    closeSidebar() {
        const sidebar = document.querySelector('.sidebar');
        const overlay = document.querySelector('.sidebar-overlay');
        
        sidebar?.classList.remove('open');
        overlay?.classList.remove('show');
        document.body.style.overflow = '';
    }

    /**
     * Setup sidebar event listeners
     */
    setupSidebar() {
        // Mobile menu toggle button
        const mobileMenuBtn = document.getElementById('mobileMenuBtn');
        if (mobileMenuBtn) {
            mobileMenuBtn.addEventListener('click', () => this.toggleSidebar());
        }        // Close sidebar when clicking outside on mobile
        document.addEventListener('click', (e) => {
            const sidebar = document.querySelector('.sidebar');
            const mobileMenuBtn = document.getElementById('mobileMenuBtn');
            
            if (window.innerWidth <= 768 && 
                sidebar?.classList.contains('open') &&
                !sidebar.contains(e.target) &&
                e.target !== mobileMenuBtn &&
                !mobileMenuBtn?.contains(e.target)) {
                this.closeSidebar();
            }
        });

        // Handle escape key
        document.addEventListener('keydown', (e) => {
            if (e.key === 'Escape') {
                this.closeSidebar();
            }
        });

        // Handle window resize
        window.addEventListener('resize', () => {
            if (window.innerWidth > 768) {
                this.closeSidebar();
            }
        });

        // Setup chat history items
        this.setupChatHistory();
    }    /**
     * Setup chat history functionality
     */
    setupChatHistory() {
        const historyItems = document.querySelectorAll('.chat-item');
        historyItems.forEach(item => {
            // Click handler
            item.addEventListener('click', (e) => {
                this.handleChatItemSelection(e, item, historyItems);
            });
            
            // Keyboard handler for accessibility
            item.addEventListener('keydown', (e) => {
                if (e.key === 'Enter' || e.key === ' ') {
                    e.preventDefault();
                    this.handleChatItemSelection(e, item, historyItems);
                }
            });
        });
    }

    /**
     * Handle chat item selection (click or keyboard)
     */
    handleChatItemSelection(e, item, historyItems) {
        e.preventDefault();
        
        // Remove active class from all items
        historyItems.forEach(i => i.classList.remove('active'));
        
        // Add active class to selected item
        item.classList.add('active');
        
        // Load chat history (placeholder)
        const chatId = item.dataset.chatId || item.querySelector('.chat-item-title')?.textContent || 'unknown';
        this.loadChatHistory(chatId);
        
        // Close sidebar on mobile after selection
        if (window.innerWidth <= 768) {
            this.closeSidebar();
        }
    }

    /**
     * Load chat history (placeholder)
     * @param {string} chatId - ID của chat cần load
     */
    loadChatHistory(chatId) {
        // TODO: Implement actual chat history loading
        console.log(`Loading chat history: ${chatId}`);
        this.addSystemMessage(`Đã chuyển sang cuộc trò chuyện: ${chatId}`);
    }

    // ...existing code...
}

// Global functions for HTML onclick handlers
window.clearChat = function() {
    if (window.polymindChat) {
        if (confirm('Bạn có chắc muốn xóa toàn bộ lịch sử chat?')) {
            window.polymindChat.clearChat();
        }
    }
};

window.exportChat = function() {
    if (window.polymindChat) {
        window.polymindChat.exportChat();
    }
};

// Initialize chat when DOM is loaded
document.addEventListener('DOMContentLoaded', () => {
    window.polymindChat = new PolyMindChat();
    
    // Add keyboard shortcuts
    document.addEventListener('keydown', (e) => {
        // Ctrl/Cmd + K to focus input
        if ((e.ctrlKey || e.metaKey) && e.key === 'k') {
            e.preventDefault();
            document.getElementById('chatInput').focus();
        }
        
        // Escape to blur input
        if (e.key === 'Escape') {
            document.getElementById('chatInput').blur();
        }
    });
});

// Expose for debugging
window.PolyMindChat = {
    instance: null,
    version: '1.0.0',
    debug: () => window.polymindChat ? window.polymindChat.getDebugInfo() : null
};
