services:

  odoo:
    container_name: odoo_15
    image: odoo:15.0
    volumes:
      - ./addons:/mnt/extra-addons # contain odoo dev modules
      - ./conf:/etc/odoo # contain config and log
      - ./web-data:/var/lib/odoo # contain odoo web data
      - ./log:/var/log/odoo # contain odoo log data
    ports:
      - "8069:8069" # web
      - "8172:8072" # web
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mcp_net
    restart: always
    # Chờ PostgreSQL container được khởi động
    # external_links:
    #   - postgresql:db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8069"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
      
networks:
  mcp_net:
    external: true


# docker restart odoo_15
# docker compose -f mcp-server/odoo/odoo_v15/docker-compose.yml up -d 
# docker compose -f mcp-server/odoo/odoo_v15/docker-compose.yml restart 
# docker compose -f mcp-server/odoo/odoo_v15/docker-compose.yml stop

# On Linux, set permissions for web-data directory:
# sudo chown -R 1000:1000 ./web-data
# sudo chmod -R 755 ./web-data

# On Windows, ensure the user running Docker has full access to the web-data folder.
# Trên Windows, dùng PowerShell để cấp quyền truy cập đầy đủ cho thư mục web-data:
# Mở PowerShell với quyền Administrator và chạy lệnh sau:
# icacls ".\web-data" /grant "${env:UserName}:(OI)(CI)F" /T
# (OI)(CI) cho phép kế thừa quyền cho tất cả file và thư mục con, F là Full control.