services:

  db:
    container_name: postgresql
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres#2025
      POSTGRES_DB: postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    restart: always # run as a service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 30s
      timeout: 10s
      retries: 5


# How to run
# docker compose -f 'docker-compose.yml' up -d --build
# docker compose -f 'docker-compose.yml' restart
# docker compose -f 'docker-compose.yml' stop