services:
  odoo:
    container_name: odoo_17
    image: odoo:17.0
    volumes:
      - ./addons:/mnt/extra-addons # contain odoo dev modules
      - ./conf:/etc/odoo # contain config and log
      - ./web-data:/var/lib/odoo # contain odoo web data
      - ./log:/var/log/odoo # contain odoo log data
    ports:
      - "8017:8069" # web
      - "8372:8072" # longpolling
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mcp_net
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8069"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
networks:
  mcp_net:
    external: true



# docker restart odoo_17
# docker compose -f mcp-server/odoo/odoo_v17/docker-compose.yml up -d 
# docker compose -f mcp-server/odoo/odoo_v17/docker-compose.yml restart 
# docker compose -f mcp-server/odoo/odoo_v17/docker-compose.yml stop

# mkdir web-data
# On Linux, set permissions for web-data directory:
# sudo chown -R 1000:1000 ./web-data
# sudo chmod -R 755 ./web-data

# On Windows, ensure the user running Docker has full access to the web-data folder.
# Trên Windows, dùng PowerShell để cấp quyền truy cập đầy đủ cho thư mục web-data:
# Mở PowerShell với quyền Administrator và chạy lệnh sau:
# icacls ".\web-data" /grant "${env:UserName}:(OI)(CI)F" /T
# (OI)(CI) cho phép kế thừa quyền cho tất cả file và thư mục con, F là Full control.